blank_issues_enabled: true
contact_links:
  - name: Discord Server
    url: https://www.discord.gg/vPTUZcvXjg
    about: Need extra assistance? Get in touch with developers through our Discord Server.