name: "⭐ Feature Request"
description: Create an issue for a feature request.
title: "<title>"
labels: [
  "Feature",
  "New Issue"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Please provide a brief explanation of the request.
    validations:
      required: true
  - type: textarea
    id: reasonings
    attributes:
      label: "Reasonings"
      description: Please provide reasons why your request should be taken into account.
    validations:
      required: true